spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo?useSSL=false&serverTimezone=UTC
    username: root
    password: your password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
