spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Mine333@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
